https://www.kaggle.com/competitions/tabular-playground-series-nov-2022/

In [91]:
#! pip3 install pandas
#! pip3 install scikit-learn

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 1.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 4.5 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 3.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 6.2 MB/s eta 0:00:0000:0100:01


In [5]:
#! unzip tabular-playground-series-nov-2022.zip

Archive:  tabular-playground-series-nov-2022.zip
  inflating: sample_submission.csv   
  inflating: submission_files/0.6222863195.csv  
  inflating: submission_files/0.6223807245.csv  
  inflating: submission_files/0.6225426578.csv  
  inflating: submission_files/0.6247722291.csv  
  inflating: submission_files/0.6253455681.csv  
  inflating: submission_files/0.6254850917.csv  
  inflating: submission_files/0.6255093621.csv  
  inflating: submission_files/0.6260141578.csv  
  inflating: submission_files/0.6263493693.csv  
  inflating: submission_files/0.6272779211.csv  
  inflating: submission_files/0.6272932068.csv  
  inflating: submission_files/0.6278191266.csv  
  inflating: submission_files/0.6286579774.csv  
  inflating: submission_files/0.6288297558.csv  
  inflating: submission_files/0.6288608516.csv  
  inflating: submission_files/0.6294457895.csv  
  inflating: submission_files/0.6297384065.csv  
  inflating: submission_files/0.6301504673.csv  
  inflating: submission_files/0

In [158]:
import os
from pathlib import Path
import pandas as pd # Библиотека Pandas для работы с табличными данным
#from google.colab import files  # чтобы загружать файлы в облако через проводник
import numpy as np # библиотека Numpy для операций линейной алгебры и прочего

from sklearn.model_selection import train_test_split

In [159]:
path = Path('.')

submission = pd.read_csv(path / 'sample_submission.csv', index_col='id')
labels = pd.read_csv(path / 'train_labels.csv', index_col='id')

# the ids of the submission rows (useful later)
sub_ids = submission.index

# the ids of the labeled rows (useful later)
gt_ids = labels.index 

# list of files in the submission folder
subs = sorted(os.listdir(path / 'submission_files'))

In [7]:
subs

['0.6222863195.csv',
 '0.6223807245.csv',
 '0.6225426578.csv',
 '0.6247722291.csv',
 '0.6253455681.csv',
 '0.6254850917.csv',
 '0.6255093621.csv',
 '0.6260141578.csv',
 '0.6263493693.csv',
 '0.6272779211.csv',
 '0.6272932068.csv',
 '0.6278191266.csv',
 '0.6286579774.csv',
 '0.6288297558.csv',
 '0.6288608516.csv',
 '0.6294457895.csv',
 '0.6297384065.csv',
 '0.6301504673.csv',
 '0.6312756578.csv',
 '0.6321136145.csv',
 '0.6329173956.csv',
 '0.6329211291.csv',
 '0.6335286032.csv',
 '0.6338206806.csv',
 '0.6343392765.csv',
 '0.6343846561.csv',
 '0.6349644082.csv',
 '0.6350090257.csv',
 '0.6362728614.csv',
 '0.6363549073.csv',
 '0.6371788217.csv',
 '0.6372032593.csv',
 '0.6372037651.csv',
 '0.6375467640.csv',
 '0.6388901165.csv',
 '0.6389095301.csv',
 '0.6396620930.csv',
 '0.6398920868.csv',
 '0.6404491258.csv',
 '0.6407502338.csv',
 '0.6419100341.csv',
 '0.6419834632.csv',
 '0.6426110725.csv',
 '0.6432872696.csv',
 '0.6433979742.csv',
 '0.6441247388.csv',
 '0.6447946959.csv',
 '0.645369423

In [76]:
X_all = np.array([])
for i in np.arange(len(subs)):
    tmp = pd.read_csv(path / 'submission_files' / subs[i], index_col='id')
    X_all = np.append(X_all, np.array(tmp['pred']), axis=0)

In [77]:
print(X_all.size)
print(X_all.shape)

200000000
(200000000,)


In [78]:
X_all

array([0.709336, 0.452988, 0.675462, ..., 0.572   , 0.641   , 0.575   ])

In [79]:
X_all.shape = (5000,40000)
print(X_all.size)
print(X_all.shape)

200000000
(5000, 40000)


In [80]:
X_all = X_all.transpose()
print(X_all.size)
print(X_all.shape)

200000000
(40000, 5000)


In [81]:
X_all

array([[0.709336, 0.799007, 0.851891, ..., 0.867847, 0.745888, 0.787   ],
       [0.452988, 0.364453, 0.567582, ..., 0.814229, 0.598331, 0.547   ],
       [0.675462, 0.84226 , 0.800013, ..., 0.896058, 0.855776, 0.667   ],
       ...,
       [0.577554, 0.673746, 0.760426, ..., 0.864388, 0.786978, 0.572   ],
       [0.712353, 0.791621, 0.807093, ..., 0.774977, 0.666404, 0.641   ],
       [0.483215, 0.535898, 0.606541, ..., 0.712205, 0.677456, 0.575   ]])

In [85]:
X_all_df = pd.DataFrame(X_all)
X_all_df

0         1         2         3         4         5         6     \
0      0.709336  0.799007  0.851891  0.537158  0.623930  0.705970  0.503437   
1      0.452988  0.364453  0.567582  0.354468  0.513818  0.584119  0.454809   
2      0.675462  0.842260  0.800013  0.525229  0.692071  0.715418  0.651008   
3      0.481046  0.577118  0.683032  0.541356  0.630088  0.664514  0.413373   
4      0.957339  0.910337  0.917322  0.874487  0.787595  0.854273  0.843846   
...         ...       ...       ...       ...       ...       ...       ...   
39995  0.382515  0.288985  0.483297  0.281330  0.414223  0.463336  0.390367   
39996  0.352498  0.300423  0.594827  0.345519  0.488960  0.506300  0.216482   
39997  0.577554  0.673746  0.760426  0.483366  0.682265  0.663974  0.448841   
39998  0.712353  0.791621  0.807093  0.809911  0.654159  0.667119  0.497323   
39999  0.483215  0.535898  0.606541  0.451370  0.540206  0.578420  0.338534   

           7         8         9     ...      4990      4991      4992  \
0      0.633185  0.641550  0.666604  ...  0.769207  0.750250  0.663370   
1      0.238501  0.472171  0.522314  ...  0.640052  0.794052  0.721298   
2      0.609124  0.691198  0.609994  ...  0.812841  0.779859  0.865657   
3      0.508210  0.526140  0.584565  ...  0.824703  0.799698  0.800130   
4      0.876749  0.821128  0.913054  ...  0.934803  0.900150  0.960911   
...         ...       ...       ...  ...       ...       ...       ...   
39995  0.229408  0.455481  0.323629  ...  0.561950  0.654353  0.614568   
39996  0.291425  0.471500  0.315838  ...  0.584715  0.620182  0.635899   
39997  0.537298  0.575501  0.606992  ...  0.739480  0.760507  0.774452   
39998  0.950074  0.520980  0.545782  ...  0.698287  0.713176  0.786973   
39999  0.669546  0.506588  0.374203  ...  0.639991  0.560201  0.559546   

           4993      4994      4995      4996      4997      4998   4999  
0      0.739333  0.822384  0.749498  0.729800  0.867847  0.745888  0.787  
1      0.804369  0.620626  0.733606  0.816942  0.814229  0.598331  0.547  
2      0.828493  0.763010  0.802883  0.806891  0.896058  0.855776  0.667  
3      0.716604  0.603779  0.708499  0.844837  0.853057  0.850657  0.622  
4      0.906037  0.961240  0.935608  0.889757  0.978505  0.953681  0.934  
...         ...       ...       ...       ...       ...       ...    ...  
39995  0.606837  0.474038  0.578634  0.584544  0.542198  0.542056  0.266  
39996  0.584809  0.677014  0.617092  0.607261  0.577821  0.589929  0.725  
39997  0.817324  0.802529  0.815348  0.712255  0.864388  0.786978  0.572  
39998  0.778239  0.813394  0.781050  0.618386  0.774977  0.666404  0.641  
39999  0.534714  0.730741  0.537760  0.629192  0.712205  0.677456  0.575  

[40000 rows x 5000 columns]

In [102]:
X_all_df = X_all_df.reset_index().rename(columns={'index':'id'})

In [103]:
X_all_df

id         0         1         2         3         4         5  \
0          0  0.709336  0.799007  0.851891  0.537158  0.623930  0.705970   
1          1  0.452988  0.364453  0.567582  0.354468  0.513818  0.584119   
2          2  0.675462  0.842260  0.800013  0.525229  0.692071  0.715418   
3          3  0.481046  0.577118  0.683032  0.541356  0.630088  0.664514   
4          4  0.957339  0.910337  0.917322  0.874487  0.787595  0.854273   
...      ...       ...       ...       ...       ...       ...       ...   
39995  39995  0.382515  0.288985  0.483297  0.281330  0.414223  0.463336   
39996  39996  0.352498  0.300423  0.594827  0.345519  0.488960  0.506300   
39997  39997  0.577554  0.673746  0.760426  0.483366  0.682265  0.663974   
39998  39998  0.712353  0.791621  0.807093  0.809911  0.654159  0.667119   
39999  39999  0.483215  0.535898  0.606541  0.451370  0.540206  0.578420   

              6         7         8  ...      4990      4991      4992  \
0      0.503437  0.633185  0.641550  ...  0.769207  0.750250  0.663370   
1      0.454809  0.238501  0.472171  ...  0.640052  0.794052  0.721298   
2      0.651008  0.609124  0.691198  ...  0.812841  0.779859  0.865657   
3      0.413373  0.508210  0.526140  ...  0.824703  0.799698  0.800130   
4      0.843846  0.876749  0.821128  ...  0.934803  0.900150  0.960911   
...         ...       ...       ...  ...       ...       ...       ...   
39995  0.390367  0.229408  0.455481  ...  0.561950  0.654353  0.614568   
39996  0.216482  0.291425  0.471500  ...  0.584715  0.620182  0.635899   
39997  0.448841  0.537298  0.575501  ...  0.739480  0.760507  0.774452   
39998  0.497323  0.950074  0.520980  ...  0.698287  0.713176  0.786973   
39999  0.338534  0.669546  0.506588  ...  0.639991  0.560201  0.559546   

           4993      4994      4995      4996      4997      4998   4999  
0      0.739333  0.822384  0.749498  0.729800  0.867847  0.745888  0.787  
1      0.804369  0.620626  0.733606  0.816942  0.814229  0.598331  0.547  
2      0.828493  0.763010  0.802883  0.806891  0.896058  0.855776  0.667  
3      0.716604  0.603779  0.708499  0.844837  0.853057  0.850657  0.622  
4      0.906037  0.961240  0.935608  0.889757  0.978505  0.953681  0.934  
...         ...       ...       ...       ...       ...       ...    ...  
39995  0.606837  0.474038  0.578634  0.584544  0.542198  0.542056  0.266  
39996  0.584809  0.677014  0.617092  0.607261  0.577821  0.589929  0.725  
39997  0.817324  0.802529  0.815348  0.712255  0.864388  0.786978  0.572  
39998  0.778239  0.813394  0.781050  0.618386  0.774977  0.666404  0.641  
39999  0.534714  0.730741  0.537760  0.629192  0.712205  0.677456  0.575  

[40000 rows x 5001 columns]

In [104]:
X_all_df.to_csv('all_submissions.csv', sep = ',', index=False)

In [160]:
X_all_df = pd.read_csv('all_submissions.csv', delimiter = ',', low_memory=False)

In [4]:
sub_ids

Index([20000, 20001, 20002, 20003, 20004, 20005, 20006, 20007, 20008, 20009,
       ...
       39990, 39991, 39992, 39993, 39994, 39995, 39996, 39997, 39998, 39999],
      dtype='int64', name='id', length=20000)

In [5]:
gt_ids

Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,
       ...
       19990, 19991, 19992, 19993, 19994, 19995, 19996, 19997, 19998, 19999],
      dtype='int64', name='id', length=20000)

In [6]:
labels

label
id          
0          0
1          1
2          1
3          1
4          0
...      ...
19995      1
19996      1
19997      0
19998      0
19999      1

[20000 rows x 1 columns]

In [161]:
labels1 = labels.reset_index()

In [8]:
labels1

id  label
0          0      0
1          1      1
2          2      1
3          3      1
4          4      0
...      ...    ...
19995  19995      1
19996  19996      1
19997  19997      0
19998  19998      0
19999  19999      1

[20000 rows x 2 columns]

In [175]:
TEST_SIZE = float(0.0)
SEED = 42
EPOCH = 9

In [178]:
if TEST_SIZE > 0:
    train_ids, test_ids, train_labels, test_labels = \
        train_test_split(labels1['id'], labels1['label'], test_size=TEST_SIZE, random_state=SEED, stratify=labels1['label'])
    df_train = X_all_df[X_all_df['id'].isin(train_ids)]
    df_test = X_all_df[X_all_df['id'].isin(test_ids)]
else:
    train_ids, test_ids, train_labels, test_labels = labels1['id'], pd.Series(), labels1['label'], pd.Series()
    df_train = X_all_df[0:20000]
    df_test = X_all_df[0:0]

In [165]:
df_train

id         0         1         2         3         4         5  \
0          0  0.709336  0.799007  0.851891  0.537158  0.623930  0.705970   
1          1  0.452988  0.364453  0.567582  0.354468  0.513818  0.584119   
2          2  0.675462  0.842260  0.800013  0.525229  0.692071  0.715418   
3          3  0.481046  0.577118  0.683032  0.541356  0.630088  0.664514   
4          4  0.957339  0.910337  0.917322  0.874487  0.787595  0.854273   
...      ...       ...       ...       ...       ...       ...       ...   
19995  19995  0.685909  0.917957  0.794700  0.744906  0.725922  0.817050   
19996  19996  0.645524  0.510220  0.609820  0.744514  0.592150  0.644032   
19997  19997  0.733537  0.930449  0.898760  0.775717  0.763998  0.864716   
19998  19998  0.487501  0.534317  0.684613  0.558547  0.562970  0.680136   
19999  19999  0.972671  0.964412  0.994938  0.955053  0.814175  0.868523   

              6         7         8  ...      4990      4991      4992  \
0      0.503437  0.633185  0.641550  ...  0.769207  0.750250  0.663370   
1      0.454809  0.238501  0.472171  ...  0.640052  0.794052  0.721298   
2      0.651008  0.609124  0.691198  ...  0.812841  0.779859  0.865657   
3      0.413373  0.508210  0.526140  ...  0.824703  0.799698  0.800130   
4      0.843846  0.876749  0.821128  ...  0.934803  0.900150  0.960911   
...         ...       ...       ...  ...       ...       ...       ...   
19995  0.686307  0.865584  0.642965  ...  0.835995  0.895738  0.884344   
19996  0.384421  0.493256  0.434521  ...  0.711924  0.754772  0.713554   
19997  0.861709  0.756532  0.704467  ...  0.936290  0.846224  0.932680   
19998  0.651311  0.499756  0.549595  ...  0.699303  0.768244  0.755810   
19999  0.961511  0.976619  0.823562  ...  1.022402  0.924382  0.995179   

           4993      4994      4995      4996      4997      4998   4999  
0      0.739333  0.822384  0.749498  0.729800  0.867847  0.745888  0.787  
1      0.804369  0.620626  0.733606  0.816942  0.814229  0.598331  0.547  
2      0.828493  0.763010  0.802883  0.806891  0.896058  0.855776  0.667  
3      0.716604  0.603779  0.708499  0.844837  0.853057  0.850657  0.622  
4      0.906037  0.961240  0.935608  0.889757  0.978505  0.953681  0.934  
...         ...       ...       ...       ...       ...       ...    ...  
19995  0.789796  0.936529  0.822425  0.889757  0.908659  0.851747  0.700  
19996  0.679688  0.734107  0.650449  0.794670  0.745623  0.551695  0.254  
19997  0.907043  0.932548  0.890430  0.812895  0.951437  0.932013  0.744  
19998  0.725308  0.712482  0.660420  0.794832  0.730376  0.721360  0.513  
19999  0.990802  0.985653  0.989982  0.920549  0.987774  1.023530  0.889  

[20000 rows x 5001 columns]

In [182]:
df_test

Empty DataFrame
Columns: [id, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, ...]
Index: []

[0 rows x 5001 columns]

In [181]:
train_labels

0        0
1        1
2        1
3        1
4        0
        ..
19995    1
19996    1
19997    0
19998    0
19999    1
Name: label, Length: 20000, dtype: int64

In [183]:
x_train = df_train.loc[:, '0':].to_numpy()
y_train = labels1[labels1['id'].isin(train_ids)]['label'].to_numpy()

x_test = df_test.loc[:, '0':].to_numpy()
y_test = labels1[labels1['id'].isin(test_ids)]['label'].to_numpy()

In [189]:
%%time
from sklearn.neural_network import MLPClassifier  # многослойный персептрон (просто много полносвязных слоев)
clf = MLPClassifier(hidden_layer_sizes=(5000,), max_iter=EPOCH, random_state=SEED, verbose=True)
clf.fit(x_train, y_train)

Iteration 1, loss = 1.10576879
Iteration 2, loss = 0.59486291
Iteration 3, loss = 0.56259967
Iteration 4, loss = 0.57352617
Iteration 5, loss = 0.54879682
Iteration 6, loss = 0.55347861
Iteration 7, loss = 0.55612338
Iteration 8, loss = 0.55563178
Iteration 9, loss = 0.56166358
CPU times: user 37min 42s, sys: 19min 39s, total: 57min 22s
Wall time: 19min 37s


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (9) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(5000,), max_iter=9, random_state=42,
              verbose=True)

In [114]:
test_pred = clf.predict(x_test)

In [115]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, test_pred)

0.703

In [116]:
test_pred

array([1, 1, 1, ..., 1, 0, 1])

In [117]:
from sklearn.metrics import log_loss
score = log_loss(y_test, test_pred)
score

10.704965056567794

0.2, 8, 0.67825
0.2, 9, 0.71125
0.2, 10, 0.70975
0.2, 11, 0.70425
0.2, 12, 0.694

0.2 5000 1  0.527 0.6774602731825602
0.2 5000 15 0.71175 0.5485058586328067
0.2 5000 20 0.69275 0.5574607153918698

In [118]:
y_prob = clf.predict_proba(x_test)

In [190]:
clf.loss_

0.561663578911858

In [120]:
y_prob

array([[0.38064907, 0.61935093],
       [0.13388575, 0.86611425],
       [0.24181479, 0.75818521],
       ...,
       [0.32440281, 0.67559719],
       [0.62690468, 0.37309532],
       [0.08254244, 0.91745756]])

In [107]:
0.63633875 + 0.36366125

1.0

In [105]:
y_prob.shape

(4000, 2)

In [106]:
y_test.shape

(4000,)

In [110]:
y_prob.transpose()[0]

array([0.63633875, 0.61503754, 0.55354282, ..., 0.6418905 , 0.78507412,
       0.58001977])

In [123]:
score = log_loss(y_test, y_prob.transpose()[1])
score

0.548068671881822

In [191]:
log_loss(y_train, clf.predict_proba(x_train).transpose()[1])

0.5358572583542549

In [86]:
from datetime import datetime

In [96]:
mlp_stat_df = pd.DataFrame(columns=['iteration', 'duration', 'train_loss', 'test_accuracy_score', 'test_log_loss'])
for i in range(1,25):
    start_date = datetime.now()
    clf = MLPClassifier(hidden_layer_sizes=(5000,), max_iter=i, random_state=SEED)
    clf.fit(x_train, y_train)
    iter_res = [i, datetime.now() - start_date,
                clf.loss_,
                accuracy_score(y_test, clf.predict(x_test)),
                log_loss(y_test, clf.predict_proba(x_test))]
    mlp_stat_df.loc[len(mlp_stat_df)] = iter_res
    print(iter_res)

/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1) reached and the optimization hasn't converged yet.
  warnings.warn(


[1, datetime.timedelta(seconds=76, microseconds=50056), 1.6041600374220581, 0.527, 0.6774602731825602]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(


[2, datetime.timedelta(seconds=140, microseconds=986018), 0.5833649756327373, 0.6915, 0.5633627717296107]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3) reached and the optimization hasn't converged yet.
  warnings.warn(


[3, datetime.timedelta(seconds=180, microseconds=415025), 0.6141317010681722, 0.69725, 0.588540468777612]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (4) reached and the optimization hasn't converged yet.
  warnings.warn(


[4, datetime.timedelta(seconds=241, microseconds=157617), 0.5927856636771264, 0.70975, 0.5636795422531325]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (5) reached and the optimization hasn't converged yet.
  warnings.warn(


[5, datetime.timedelta(seconds=301, microseconds=67797), 0.5597382919609966, 0.68775, 0.5766411811666465]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (6) reached and the optimization hasn't converged yet.
  warnings.warn(


[6, datetime.timedelta(seconds=352, microseconds=990051), 0.576282779520816, 0.6935, 0.5575226335449216]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (7) reached and the optimization hasn't converged yet.
  warnings.warn(


[7, datetime.timedelta(seconds=410, microseconds=865460), 0.5693335231178083, 0.69275, 0.5625097138012907]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (8) reached and the optimization hasn't converged yet.
  warnings.warn(


[8, datetime.timedelta(seconds=466, microseconds=346409), 0.5608500523664042, 0.70275, 0.5762088311943069]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (9) reached and the optimization hasn't converged yet.
  warnings.warn(


[9, datetime.timedelta(seconds=527, microseconds=340853), 0.5571184888168256, 0.703, 0.548068671881822]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


[10, datetime.timedelta(seconds=584, microseconds=190877), 0.5665889450865276, 0.6945, 0.5582716853010039]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (11) reached and the optimization hasn't converged yet.
  warnings.warn(


[11, datetime.timedelta(seconds=644, microseconds=343766), 0.5540890627585554, 0.708, 0.569899616166937]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (12) reached and the optimization hasn't converged yet.
  warnings.warn(


[12, datetime.timedelta(seconds=702, microseconds=178091), 0.5545415546121482, 0.69575, 0.5534449263085787]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (13) reached and the optimization hasn't converged yet.
  warnings.warn(


[13, datetime.timedelta(seconds=762, microseconds=133110), 0.5451508422013507, 0.66125, 0.6296097305143481]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (14) reached and the optimization hasn't converged yet.
  warnings.warn(


[14, datetime.timedelta(seconds=819, microseconds=945680), 0.570418629295418, 0.68625, 0.5723393737982316]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (15) reached and the optimization hasn't converged yet.
  warnings.warn(


[15, datetime.timedelta(seconds=882, microseconds=573164), 0.5464586722992459, 0.71175, 0.5485058586328067]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (16) reached and the optimization hasn't converged yet.
  warnings.warn(


[16, datetime.timedelta(seconds=936, microseconds=189595), 0.5538060401622668, 0.70325, 0.5477874998212632]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (17) reached and the optimization hasn't converged yet.
  warnings.warn(


[17, datetime.timedelta(seconds=997, microseconds=133668), 0.5541929218841635, 0.707, 0.5425356653453035]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (18) reached and the optimization hasn't converged yet.
  warnings.warn(


[18, datetime.timedelta(seconds=1052, microseconds=893332), 0.5720469512664407, 0.694, 0.5523391696808727]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (19) reached and the optimization hasn't converged yet.
  warnings.warn(


[19, datetime.timedelta(seconds=1115, microseconds=540167), 0.5397737360409461, 0.706, 0.5433506091562549]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(


[20, datetime.timedelta(seconds=1176, microseconds=468519), 0.540703214839552, 0.69275, 0.5574607153918698]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (21) reached and the optimization hasn't converged yet.
  warnings.warn(


[21, datetime.timedelta(seconds=1236, microseconds=1308), 0.5375752854911252, 0.707, 0.5419957950164735]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (22) reached and the optimization hasn't converged yet.
  warnings.warn(


[22, datetime.timedelta(seconds=1293, microseconds=374727), 0.5384729971585854, 0.703, 0.5485375128039637]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (23) reached and the optimization hasn't converged yet.
  warnings.warn(


[23, datetime.timedelta(seconds=1356, microseconds=20572), 0.5448196782308032, 0.712, 0.5483665072545236]


/home/user03/git/MLOps2_M2.2_Kaggle/.venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (24) reached and the optimization hasn't converged yet.
  warnings.warn(


[24, datetime.timedelta(seconds=1419, microseconds=381626), 0.5432381566746705, 0.7095, 0.5603923027345428]


In [97]:
mlp_stat_df

iteration               duration  train_loss  test_accuracy_score  \
0           1 0 days 00:01:16.050056    1.604160              0.52700   
1           2 0 days 00:02:20.986018    0.583365              0.69150   
2           3 0 days 00:03:00.415025    0.614132              0.69725   
3           4 0 days 00:04:01.157617    0.592786              0.70975   
4           5 0 days 00:05:01.067797    0.559738              0.68775   
5           6 0 days 00:05:52.990051    0.576283              0.69350   
6           7 0 days 00:06:50.865460    0.569334              0.69275   
7           8 0 days 00:07:46.346409    0.560850              0.70275   
8           9 0 days 00:08:47.340853    0.557118              0.70300   
9          10 0 days 00:09:44.190877    0.566589              0.69450   
10         11 0 days 00:10:44.343766    0.554089              0.70800   
11         12 0 days 00:11:42.178091    0.554542              0.69575   
12         13 0 days 00:12:42.133110    0.545151              0.66125   
13         14 0 days 00:13:39.945680    0.570419              0.68625   
14         15 0 days 00:14:42.573164    0.546459              0.71175   
15         16 0 days 00:15:36.189595    0.553806              0.70325   
16         17 0 days 00:16:37.133668    0.554193              0.70700   
17         18 0 days 00:17:32.893332    0.572047              0.69400   
18         19 0 days 00:18:35.540167    0.539774              0.70600   
19         20 0 days 00:19:36.468519    0.540703              0.69275   
20         21 0 days 00:20:36.001308    0.537575              0.70700   
21         22 0 days 00:21:33.374727    0.538473              0.70300   
22         23 0 days 00:22:36.020572    0.544820              0.71200   
23         24 0 days 00:23:39.381626    0.543238              0.70950   

    test_log_loss  
0        0.677460  
1        0.563363  
2        0.588540  
3        0.563680  
4        0.576641  
5        0.557523  
6        0.562510  
7        0.576209  
8        0.548069  
9        0.558272  
10       0.569900  
11       0.553445  
12       0.629610  
13       0.572339  
14       0.548506  
15       0.547787  
16       0.542536  
17       0.552339  
18       0.543351  
19       0.557461  
20       0.541996  
21       0.548538  
22       0.548367  
23       0.560392

In [98]:
len(mlp_stat_df)

24

In [95]:
print(mlp_stat_df[0:1])

   iteration               duration  train_loss  test_accuracy_score  \
0          1 0 days 00:01:17.215036     1.60416                0.527   

   test_log_loss  
0        0.67746  


In [192]:
df_submit = X_all_df[X_all_df['id'].isin(sub_ids)]
x_submit = df_submit.loc[:, '0':].to_numpy()
y_submit_pred = clf.predict_proba(x_submit)

In [124]:
y_submit_pred.transpose()[1]

array([0.46089085, 0.60973084, 0.14877749, ..., 0.40249226, 0.42045345,
       0.29998462])

In [195]:
sub_ids

Index([20000, 20001, 20002, 20003, 20004, 20005, 20006, 20007, 20008, 20009,
       ...
       39990, 39991, 39992, 39993, 39994, 39995, 39996, 39997, 39998, 39999],
      dtype='int64', name='id', length=20000)

In [193]:
submit_pred = np.hstack((np.array(sub_ids),y_submit_pred.transpose()[1]))

In [194]:
submit_pred.shape = (2,20000)

In [196]:
submit_pred.transpose()

array([[2.00000000e+04, 6.11249681e-01],
       [2.00010000e+04, 7.23438999e-01],
       [2.00020000e+04, 2.27755869e-01],
       ...,
       [3.99970000e+04, 5.39054359e-01],
       [3.99980000e+04, 5.73658453e-01],
       [3.99990000e+04, 4.16193213e-01]])

In [197]:
df_submit_pred = pd.DataFrame(submit_pred.transpose(), columns = ['id','pred'])

In [198]:
df_submit_pred['id'] = df_submit_pred['id'].astype('int64')

In [199]:
df_submit_pred

id      pred
0      20000  0.611250
1      20001  0.723439
2      20002  0.227756
3      20003  0.359417
4      20004  0.055551
...      ...       ...
19995  39995  0.202070
19996  39996  0.347040
19997  39997  0.539054
19998  39998  0.573658
19999  39999  0.416193

[20000 rows x 2 columns]

In [200]:
df_submit_pred.to_csv('submission_ipynb.csv', sep = ',', index=False)